### ISSUE TITLE
主题ssr下不工作

### ISSUE THREAD

**Issue by diauweb** [OI-wiki/oi-wiki-ng#171]

**Comment by Ir1d** [comment]
初步定位： caused by #137

9f9fc5b build 后界面不正常，而前一个 commit 3e2f07e858262f85b5d298de46d1285f1fd72310 工作正常

**Comment by Ir1d** [comment]
https://material-ui.com/guides/server-rendering/

**Comment by diauweb** [comment]
88089f4eb312421cd73937528ca320996f4cc412
