### ISSUE TITLE
SSR 有 flicker 现象

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/oi-wiki-ng#173]
待 check： https://material-ui.com/guides/server-rendering/

**Comment by Enter-tainer** [comment]
fixed

**Comment by diauweb** [comment]
88089f4eb312421cd73937528ca320996f4cc412

**Comment by Ir1d** [comment]
现在还会有 flicker 现象，之前 link 的那个页面貌似是需要有一个活的 server 来改 css，如果我们现在这种实现应该只有首屏闪一下。（ note: mkdocs 也会闪）
